from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

PROJECT_ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = PROJECT_ROOT / ".env"
HISTORY_PATH = PROJECT_ROOT / "release-history.jsonl"
SMOKE_SCRIPT = PROJECT_ROOT / "scripts" / "smoke_test.py"


class ReleaseError(RuntimeError):
    """Raised when a build, deployment, smoke test or rollback fails."""


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def write_env(path: Path, values: dict[str, str]) -> None:
    ordered = [
        "API_IMAGE",
        "API_TAG",
        "API_PORT",
        "EXPECTED_SERVICE_VERSION",
        "RELEASE_CHANNEL",
        "SIMULATE_STARTUP_FAILURE",
    ]
    lines = ["# Generated by scripts/release_manager.py; do not commit."]
    for key in ordered:
        if key in values:
            lines.append(f"{key}={values[key]}")
    for key in sorted(set(values) - set(ordered)):
        lines.append(f"{key}={values[key]}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def record_event(event: str, **details: object) -> None:
    entry = {"timestamp": utc_now(), "event": event, **details}
    with HISTORY_PATH.open("a", encoding="utf-8") as stream:
        stream.write(json.dumps(entry, ensure_ascii=False) + "\n")


def run(command: Iterable[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    command_list = list(command)
    print("+", " ".join(command_list))
    result = subprocess.run(
        command_list,
        cwd=PROJECT_ROOT,
        text=True,
        capture_output=False,
    )
    if check and result.returncode != 0:
        raise ReleaseError(f"Command failed with code {result.returncode}: {' '.join(command_list)}")
    return result


def docker_available() -> None:
    try:
        result = subprocess.run(
            ["docker", "compose", "version"],
            cwd=PROJECT_ROOT,
            text=True,
            capture_output=True,
        )
    except FileNotFoundError as error:
        raise ReleaseError("Docker CLI is not installed or not available in PATH") from error
    if result.returncode != 0:
        raise ReleaseError(f"Docker Compose is unavailable: {result.stderr.strip()}")


def build_image(
    *,
    tag: str,
    service_version: str,
    model_version: str,
    model_c: float,
    image: str = "mlops-course-api",
) -> None:
    docker_available()
    record_event(
        "build_started",
        image=image,
        tag=tag,
        service_version=service_version,
        model_version=model_version,
        model_c=model_c,
    )
    run(
        [
            "docker",
            "build",
            "--tag",
            f"{image}:{tag}",
            "--build-arg",
            f"SERVICE_VERSION={service_version}",
            "--build-arg",
            f"MODEL_VERSION={model_version}",
            "--build-arg",
            f"MODEL_C={model_c}",
            ".",
        ]
    )
    record_event("build_succeeded", image=image, tag=tag, service_version=service_version)


def smoke(expected_version: str, *, timeout: float = 45.0) -> None:
    run(
        [
            sys.executable,
            str(SMOKE_SCRIPT),
            "--base-url",
            "http://127.0.0.1:8000",
            "--expected-service-version",
            expected_version,
            "--timeout",
            str(timeout),
        ]
    )


def compose_up() -> None:
    run(["docker", "compose", "up", "-d", "--force-recreate", "api"])


def deploy(
    *,
    tag: str,
    expected_version: str,
    image: str = "mlops-course-api",
    simulate_failure: bool = False,
    timeout: float = 45.0,
    auto_rollback: bool = True,
) -> None:
    docker_available()
    previous = read_env(ENV_PATH)
    if not previous:
        previous = {
            "API_IMAGE": image,
            "API_TAG": "stable",
            "API_PORT": "8000",
            "EXPECTED_SERVICE_VERSION": "1.0.0",
            "RELEASE_CHANNEL": "stable",
            "SIMULATE_STARTUP_FAILURE": "0",
        }

    candidate = dict(previous)
    candidate.update(
        {
            "API_IMAGE": image,
            "API_TAG": tag,
            "API_PORT": previous.get("API_PORT", "8000"),
            "EXPECTED_SERVICE_VERSION": expected_version,
            "RELEASE_CHANNEL": "candidate" if tag != "stable" else "stable",
            "SIMULATE_STARTUP_FAILURE": "1" if simulate_failure else "0",
        }
    )

    write_env(ENV_PATH, candidate)
    record_event(
        "deployment_started",
        image=image,
        tag=tag,
        expected_version=expected_version,
        simulate_failure=simulate_failure,
        previous_tag=previous.get("API_TAG"),
    )

    try:
        compose_up()
        smoke(expected_version, timeout=timeout)
    except (ReleaseError, subprocess.SubprocessError) as error:
        record_event("deployment_failed", tag=tag, reason=str(error))
        if not auto_rollback:
            raise ReleaseError(f"Deployment failed and rollback is disabled: {error}") from error

        print("Deployment failed; restoring previous release configuration.", file=sys.stderr)
        write_env(ENV_PATH, previous)
        try:
            compose_up()
            previous_version = previous.get("EXPECTED_SERVICE_VERSION", "")
            if previous_version:
                smoke(previous_version, timeout=timeout)
        except Exception as rollback_error:
            record_event("rollback_failed", reason=str(rollback_error), previous=previous)
            raise ReleaseError(
                f"Deployment failed ({error}) and rollback also failed ({rollback_error})"
            ) from rollback_error
        record_event(
            "rollback_succeeded",
            restored_tag=previous.get("API_TAG"),
            restored_version=previous.get("EXPECTED_SERVICE_VERSION"),
        )
        raise ReleaseError("Candidate failed release checks; previous release was restored") from error

    record_event("deployment_succeeded", tag=tag, service_version=expected_version)
    print(f"Deployment succeeded: {image}:{tag} ({expected_version})")


def show_status() -> None:
    values = read_env(ENV_PATH)
    print(json.dumps(values, indent=2, ensure_ascii=False))
    if HISTORY_PATH.exists():
        print("Recent events:")
        for line in HISTORY_PATH.read_text(encoding="utf-8").splitlines()[-5:]:
            print(line)


def main() -> int:
    parser = argparse.ArgumentParser(description="Educational release manager for the MLOps course")
    subparsers = parser.add_subparsers(dest="command", required=True)

    build_parser = subparsers.add_parser("build", help="Build a versioned local image")
    build_parser.add_argument("--tag", required=True)
    build_parser.add_argument("--service-version", required=True)
    build_parser.add_argument("--model-version", required=True)
    build_parser.add_argument("--model-c", type=float, default=1.0)
    build_parser.add_argument("--image", default="mlops-course-api")

    deploy_parser = subparsers.add_parser("deploy", help="Deploy a tag and rollback on failed checks")
    deploy_parser.add_argument("--tag", required=True)
    deploy_parser.add_argument("--expected-version", required=True)
    deploy_parser.add_argument("--image", default="mlops-course-api")
    deploy_parser.add_argument("--simulate-failure", action="store_true")
    deploy_parser.add_argument("--timeout", type=float, default=45.0)
    deploy_parser.add_argument("--no-rollback", action="store_true")

    subparsers.add_parser("status", help="Show current local release state")

    args = parser.parse_args()
    try:
        if args.command == "build":
            build_image(
                tag=args.tag,
                service_version=args.service_version,
                model_version=args.model_version,
                model_c=args.model_c,
                image=args.image,
            )
        elif args.command == "deploy":
            deploy(
                tag=args.tag,
                expected_version=args.expected_version,
                image=args.image,
                simulate_failure=args.simulate_failure,
                timeout=args.timeout,
                auto_rollback=not args.no_rollback,
            )
        else:
            show_status()
    except ReleaseError as error:
        print(f"RELEASE ERROR: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
